### ISSUE TITLE
iti47RequestValidator asking for responseModalityCode and responsePriorityCode

### ISSUE THREAD

**Issue by razvanTri** [IHE/ITI-Info#2]
Hello,

I've been trying to make a request to iti47 PDQV3 with the example from here: https://github.com/IHE/ITI-Info/tree/master/examples/PDQV3/01_PDQQuery1.xml. The iti47RequestValidator() from org.openehealth.ipf.platform.camel.ihe.hl7v3.PixPdqV3CamelValidators keeps giving me this error:

```
<text>Validation error at /*[local-name()='PRPA_IN201305UV02']/*[local-name()='controlActProcess']/*[local-name()='queryByParameter'] : responsePriorityCode must equal to 'I'
Validation error at /*[local-name()='PRPA_IN201305UV02']/*[local-name()='controlActProcess']/*[local-name()='queryByParameter'] : responseModalityCode must equal to 'R'</text>
```

I'm not sure why this is happening, the documentation was saying that these response codes were not required. Do you have any idea why the validator is asking for them?

The schema for it is here: https://github.com/IHE/ITI-Info/blob/master/schema/HL7V3/NE2008/multicacheschemas/PRPA_IN201305UV02.xsd. And in the type `PRPA_MT201306UV02.QueryByParameter`, it is specified that `minOccurs` is 0 for the 2 codes:
```
<xs:element name="responseModalityCode" type="CS" minOccurs="0" maxOccurs="1"/>
<xs:element name="responsePriorityCode" type="CS" minOccurs="0" maxOccurs="1"/>
```

**Comment by unixoid** [comment]
Hello Razvan

These constraints are specified in [ITI TF-2:3.47.4.1.2.2](https://profiles.ihe.net/ITI/TF/Volume2/ITI-47.html#3.47.4.1.2.2).

Best regards
Dmytro

**Comment by razvanTri** [comment]
@unixoid ok, thank you, so I guess the schema is outdated? Do you know if it will be updated in the future or not?

**Comment by unixoid** [comment]
The schema belongs to a normative edition of HL7v3 (NE 2008) which is referenced from the IHE PIXv3/PDQv3 specification and is in this sense not outdated, but an XML Schema cannot express all possible constraints -- this is why a Schematron was created in addition to the XML Schema document.
